owner: xCraimax
repo: upptime

user-agent: xCraimax

sites:
  - name: Homepage
    url: https://xcraimax.de

status-website:
  cname: status.xcraimax.de
  logoUrl: https://xcraimax.de/img/profile.png
  favicon: https://xcraimax.de/img/profile.png
  robotsText: "User-agent: * \n Disallow: /"
  name: xCraimax.de
  introTitle: "Status Monitor"
  introMessage: Hier finden Sie alle Statusmeldungen.
  theme: dark
  navbar:
    - title: Startseite
      href: https://xcraimax.de/
    - title: Kontakt
      href: mailto:admin@xcraimax.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
