owner: xCraimax
repo: upptime

user-agent: xCraimax

sites:
  - name: Homepage
    url: https://xcraimax.de/robots.txt
  - name: Urbania Nova - Minecraft
    check: "tcp-ping"
    url: 212.11.64.102
    port: 20214

status-website:
  cname: status.xcraimax.de
  logoUrl: https://xcraimax.de/img/favicon.png
  favicon: https://xcraimax.de/img/favicon.png
  robotsText: "User-agent: * \n Disallow: /"
  name: xCraimax.de | Status
  introTitle: "Status Monitor"
  introMessage: Hier finden Sie alle Statusmeldungen.
  theme: night
  navbar:
    - title: Startseite
      href: https://xcraimax.de/
    - title: Kontakt
      href: mailto:admin@xcraimax.de

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme sind betriebsbereit
  incidentReport: "Vorfallsbericht #$NUMBER →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Posts
  incidentTitle: Vorfall Details $NUMBER
  incidentDetails: Vorfall Details
  incidentFixed: Behoben
  incidentOngoing: Laufend
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: Auf GitHub anzeigen und abonnieren
  incidentCommentSummary: Gepostet am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS Posts
  liveStatus: Live-Status
  overallUptime: "Gesamtverfügbarkeit: $UPTIME"
  overallUptimeTitle: Gesamtverfügbarkeit
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7 Tage Reaktionszeit
  responseTimeMs: Reaktionszeit (ms)
  up: Aktiv
  down: Ausfall
  degraded: Störung
  ms: ms
  loading: Lade
  navGitHub: GitHub
  footer: xCraimax.de | Status
  rateLimitExceededTitle: Ratenlimit überschritten
  rateLimitExceededIntro: Sie haben die Anzahl der Anfragen überschritten, die Sie in einer Stunde stellen können. Sie müssen also warten, bevor Sie wieder auf diese Website zugreifen können. Alternativ können Sie ein persönliches GitHub-Zugriffstoken hinzufügen, um diese Website weiterhin nutzen zu können.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Website verwendet die GitHub-API, um in Echtzeit auf Daten zum Status unserer Websites zuzugreifen. Standardmäßig erlaubt GitHub jeder IP-Adresse 60 Anfragen pro Stunde, die Sie verbraucht haben.
  rateLimitExceededErrorHowCanFix: Wie kann ich das Problem beheben?
  rateLimitExceededErrorFix: Sie können noch eine Stunde warten und das Limit Ihrer IP-Adresse wird wiederhergestellt. Alternativ können Sie Ihren persönlichen GitHub-Zugriffstoken hinzufügen, der Ihnen zusätzliche 5.000 Anfragen pro Stunde ermöglicht.
  rateLimitExceededGeneratePAT: Erfahren Sie, wie Sie ein persönliches Zugriffstoken generieren
  rateLimitExceededHasSet: Sie haben einen persönlichen Zugriffstoken-Satz.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: Persönlicher GitHub-Zugriffstoken
  rateLimitExceededCopyPastePAT: Kopieren und fügen Sie Ihr Token ein
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: Beim Versuch, die neuesten Statusdetails abzurufen, ist ein Fehler aufgetreten.
  errorText: Sie können es in wenigen Augenblicken erneut versuchen.
  errorHome: Zur Homepage
  pastScheduledMaintenance: Vergangenen geplante Wartungsarbeiten
  scheduledMaintenance: Geplante Wartung
  scheduledMaintenanceSummaryStarted: Begonnen am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Begonnen am
  startsAt: Beginnt am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Vollendet
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: Allzeit
  locale: de-DE

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
